### PR TITLE
Grok podcast is no more :(

### PR DESCRIPTION
**Pull request by PotHix**

### CODE REVIEW

**Comment by HudsonSilva** [comment]
I have the episodes in my dropbox. Do you want me to zip and make it available here?

**Comment by PotHix** [comment]
@tapajos ^

**Comment by tapajos** [comment]
@HudsonSilva can you add the links here?

**Comment by PotHix** [comment]
Too old. :(

**Comment by tapajos** [comment]
@PotHix thanks

**Pull request merged**
